### ISSUE TITLE
Javascript: Inconsistent export of classes (ESM mixed with non-ESM)

### ISSUE THREAD

**Issue by jonaskello** [antlr/antlr4#3956]
The generated files for the JavaScript target uses the ES modules `export` keyword to export the parser class. So obviously the generated files are ES modules. However the other classes are not exported with the `export`  keyword but instead in a non-ESM compatible way by setting them as properties on the parser class. This is not proper exporting according to ESM syntax and makes the files hard to import from consumers that expects proper ESM syntax for all exports.

To give an example:

Grammar

```
// define a grammar called Hello
grammar Hello;
r   : 'hello' ID;
ID  : [a-z]+ ;
WS  : [ \t\r\n]+ -> skip ;
```

Generated javascript parser:

```js
// Proper ESM export with export keyword
export default class HelloParser extends antlr4.Parser {
// other stuff...

// This class is missing export keyword - This is the bug
class RContext extends antlr4.ParserRuleContext {
// other suff

// Here the RContext class is exported in a non-ESM syntax way
HelloParser.RContext = RContext; 
```

Notice that the `HelloParser` class is exported using the `export` keyword which is correct  ESM syntax. However for the context classes the `export` keyword is missing, and instead they are being set on the `HelloParser` class at the end. This is not correct ESM syntax, they should instead also be exported using the `export` keyword. 

Same example but with correct ESM exports:

```js
export default class HelloParser extends antlr4.Parser {
// other stuff...

// Notice that the class is exported using proper ESM export keyword 
export class RContext extends antlr4.ParserRuleContext {
// other suff

//  This older non-ESM way of export could be kept as-is if needed
HelloParser.RContext = RContext; 
```

So the fix is simply to just add `export` in front of all context classes. The older way to export could also be kept to be backwards compatible.

**Comment by ericvergnaud** [comment]
Many JavaScript libraries follow the same model, an example being react-bootstrap. Nothing prevents developers from using HelloParser.RContext. This is not a bug. Envoyé de mon iPhoneLe 10 nov. 2022 à 23:15, Jonas Kello ***@***.***> a écrit :﻿
Here is an example of the bug in action when using a .mjs file (which is node's standard extension for ES module files):
consumer.mjs
import { RContext } from "./HelloParser.js";

export const x = new RContext();
 $ node consumer.mjs 

import { RContext } from "./HelloParser.js";
         ^^^^^^^^
SyntaxError: The requested module './HelloParser.js' does not provide an export named 'RContext'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

**Comment by jonaskello** [comment]
If a generated file is to be considered an ES module and don't use proper ESM export style throughout the file I would consider this a bug in the file generator. If the file is not an ES module then no it is not a bug to use non-ESM export style. The use of  `export` for the parser class indicates that the file is to be considered an ES module.

Yes, nothing is stopping developers from working around the use of mixed export styles. But would it not be better to just fully support ESM style exports in the whole file?

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/index.tsx

I only see valid ESM exports in there. Since react-bootstrap seems to be using typescript I would think their output is fully ESM compatible? If the typescript compiler would output ESM JS files without proper ESM exports for all items I think that would be considered a bug in the typescript compiler.

Anyways, we could argue bug or not but that is not really helping here. Is there a chance of getting this fixed? I could try to make a PR if there is a chance of getting it accepted.

**Comment by ericvergnaud** [comment]
I'd still need to understand why anyone would want to write code such as (in your example):
`const x = new RContext();`
This is not something we're willing to support, because contexts are meant for reading parsing results only, and should only be populated by the generated parser itself.
Can you explain what you are trying to achieve ?

**Comment by jonaskello** [comment]
I get these examples are not real world but I wanted to keep them short. Perhaps a better short example would be when you want to get a certain context in a generic way from any instance that inherits from `ParserRuleContext`:

```js
import HelloParser from "./HelloParser.js";

// The variable ctx inherites ParserRuleContext
const theContext = ctx.getTypedRuleContext(HelloParser.RContext);
```

I think this is already supported since the classes are exported in non-ESM style? So my thinking is that this issue is not about supporting something new, it is just about supporting existing functionality in an ESM idiomatic way. The above works but is not idiomatic for ES modules. (In the case the above example is not supported I don't understand why the code is generated to add the context classes to the parser class?)

The idiomatic way for ES modules would be this:

```js
import * as HelloParser from "./HelloParser.js";

// The variable ctx inherites ParserRuleContext
const theContext = ctx.getTypedRuleContext(HelloParser.RContext);
```
or this

```js
import HelloParser, { RContext } from "./HelloParser.js";

// The variable ctx inherites ParserRuleContext
const theContext = ctx.getTypedRuleContext(RContext);
```

**Comment by jonaskello** [comment]
Aside from being confusing for developers that expect idiomatic ESM exports, the addition of context classes as "secret" variables on the parser class also confuses tooling such as vscode that tries to provide intellisense for what you can import.

**Comment by ericvergnaud** [comment]
I believe these concerns are fully addressed by the WIP Typescript target. We're looking for beta testers. Maybe you could try it out ? I'm not able to asses the risk of changing the JavaScript packaging, there are thousands of users out there.

**Comment by jonaskello** [comment]
This issue is not about typescript, it is about ES modules in javascript. Files produced by the typescript target would not be possible to import by javascript ES modules (eg. `.mjs` files) so the WIP typescript target would not solve this issue.

Adding `export` for the context classes is 100% backwards compatible and would not affect any existing users.

**Comment by jonaskello** [comment]
To clarify the 100% backwards compatible part. If code is generated exactly like it is tody, the only additon is `export` in front of context classes, then you could import them standard ESM way but also in the current non-ESM way.

So I propose the code is generated like this (only extra `export` is added, nothing else is changed or removed in any way):

```js
// other stuff same as before

// only added export
export class RContext extends antlr4.ParserRuleContext {

// other suff same as before including this non-ESM export:
HelloParser.RContext = RContext; 
```

Now you could use this code in the non-ESM way as before like this:

```js
import HelloParser from "./HelloParser.js";

// The variable ctx inherits ParserRuleContext
const theContext = ctx.getTypedRuleContext(HelloParser.RContext);
```

or you could use it in ESM standard way like this:

```js
import { RContext } from "./HelloParser.js";

// The variable ctx inherits ParserRuleContext
const theContext = ctx.getTypedRuleContext(RContext);
```

**Comment by ericvergnaud** [comment]
Already fixed, closing

**Comment by FallenChromium** [comment]
I think I'm still facing this issue using JavaScript target on 4.12.0
